apiVersion: {{ template "deployment.apiVersion" .}}
kind: Deployment
metadata:
   name: {{ .Release.Name}}
   namespace: {{ .Values.namespace }}
   {{- template "inventorydeps.labels" . }}
spec:
     template:
       metadata:
         name: {{ .Release.Name}}
         {{- template "inventorypods.labels" . }}
       spec:
         containers:
           {{- range $key, $value := .Values.containers }}
           - name: {{ $value.name }}
             image: {{ $value.image }}
           {{- end }}
     replicas: {{ .Values.replicas}}
     selector:
      matchLabels:
        app: {{ .Release.Name}}