apiVersion: v1
kind: Service
metadata:
  name: inventorysrv
  labels:
    app: inventorysrv
spec:
  type: NodePort
  ports:
    - name: inventorysrv
      port: 8083
      targetPort: 8083
      nodePort: 30007
  selector:
    app: inventorysrv
